language: java

addons:
  apt:
    update: true
    packages:
      - pandoc

jdk:
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
  - mkdir ghpages
  - pandoc -o ghpages/index.html README.md
  - openssl aes-256-cbc -K $encrypted_60afd10366bc_key -iv $encrypted_60afd10366bc_iv -in ghpages_secret.enc -out ghpages_secret -d

deploy:
  provider: pages:git
  edge: true
  skip_cleanup: true
  local_dir: ghpages
  deploy_key: ghpages_secret
  keep_history: true
  on:
    branch: master
